### ISSUE TITLE
Port to .NET Core?

### ISSUE THREAD

**Issue by plettb** [TwilioDevEd/ivr-phone-tree-csharp#266]
I'm trying to port this app to .NET Core, and for the most part it seems fairly straight-forward.  I have the "WelcomeController" working, and it redirects to the "MenuController", BUT the "Show" method in the "MenuController" is receiving null rather than the digit selected.  I've tried forcing a "[FromBody]", but that failed.  I tried reading the body of the message directly, and that also failed.

From what I can tell, the "TwiML" returned from the "WelcomeController" in the .NET Core version is identical to what is returned from the .NET Framework version.

Any ideas?  Any help would be much appreciated!

Thanks!

**Comment by plettb** [comment]
Here is the solution/project, ported with the fewest changes possible.
[IVRPhoneTree.zip](https://github.com/TwilioDevEd/ivr-phone-tree-csharp/files/6865683/IVRPhoneTree.zip)

**Comment by plettb** [comment]
I've created PR #274 in order to demonstrate the code.

**Comment by plettb** [comment]
I have just discovered that I can use `digits = this.Request.Form["Digits"].ToString();` to get it to work.  That feels like a kludge, but I can work with that if I have to.

**Comment by bld010** [comment]
Hi @plettb 

Can you try the following and let me know if it works for you?

In your MenuController.cs add this using statement:
`using Twilio.AspNet.Common;`

and change your `string digits` param to `VoiceRequest request`
```C#
// POST: Menu/Show 
[HttpPost("Show")] 
public TwiMLResult Show(VoiceRequest request) 
{
    var selectedOption = request.Digits;
...
}
```

Here's the [definition of VoiceRequest in the aspnet helper library](https://github.com/twilio/twilio-aspnet/blob/9bc93ce0db478a67a2b0071f9691d18b9d40ffa9/src/Twilio.AspNet.Common/VoiceRequest.cs)

**Comment by bld010** [comment]
While I was working through your branch, I also ran into a few extra issues I wanted to make you aware of:
1. I was receiving 415 Unsupported Media Type errors when using the Redirect or Gather verbs. To fix this, I added a [FromForm] attribute before the VoiceRequest parameter: 
`public TwiMLResult Interconnect([FromForm] VoiceRequest request)`
2. The phone numbers in the PhoneExchange/Interconnect endpoint are no longer working.  For now, you'll get to that point and hear "We're sorry. An application error has occurred."  I'm assuming those phone numbers were configured to <Say> something via a TwiML bin. I'll work on getting these numbers updated. In the mean time, you can change it to a TwiML.Say command or your own personal number to verify the code is working as expected.

**Comment by plettb** [comment]
@bld010 thank-you very much!

I'm sorry I was a little slow to respond - I got dragged away on something else.  Anyway, with those two fixes everything appears to work like a charm.  Thank-you very much for your help!
